[build]
  publish = "portfolio-site/dist"
  command = "cd portfolio-site && npm install && npm run build"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "max-age=31536000"
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"